export VISUAL=vim
export EDITOR="$VISUAL"

export NVM_DIR="$HOME/.nvm"
export SDKMAN_DIR="$HOME/.sdkman"
export STARSHIP_CONFIG=$HOME/Toolbox/starship/starship.toml

# Golang
export GOPATH=$HOME/.go
export PATH="$PATH:$GOPATH/bin"

# Pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PATH:$PYENV_ROOT/bin"