#!/usr/bin/env -S bash -i

set -e

echo "Enter tags: "  
read TAGS  
echo "Enter summary: "  
read SUMMARY  
echo "Enter message: "  
read MESSAGE  

stringarray=($sentence)

COMMIT_MESSAGE=""
for TAG in $TAGS
do
  COMMIT_MESSAGE+="[${TAG}]"
done
COMMIT_MESSAGE+=" ${SUMMARY}"

if [[ -z "$MESSAGE" ]]; then
  git commit -m "${COMMIT_MESSAGE}"
else
  git commit -m "${COMMIT_MESSAGE}" -m "${MESSAGE}"
fi

git push